# syntax = docker/dockerfile:1
ARG BASE=fedora:43
FROM ${BASE}

# ccache: For CI machines to decrease compile times
# cmake3: To build the lcm subproject for certain examples
# clang: For compiling code with Clang
# @development-tools: For compiling code with GCC
# doxygen: For generating documentation
# flexiblas-devel: For using support library OpenBLAS (BLAS/LAPACK)
# flexiblas-openblas-serial: For using support library OpenBLAS (BLAS/LAPACK)
# gdal-devel: Support library needed for `optional/gdal`
# glib2-devel: To build the lcm subproject for certain examples
# libasan: For compiling with Address Sanitizer to detect runtime memory errors
# libubsan: For compiling with Undefined Behavior Sanitizer to detect errors
# micro: For modifying files when using this container for development
# ninja-build: For compiling code
# python3-devel: Support library to compile the navtk Python Extension Module
# python3-numpy: Support library to compile the navtk Python Extension Module
# python3-pip: For installing pip packages (see requirements.txt)
# sudo: For privilege escalation when using this container for development
# texlive: For generating documentation
RUN dnf install -y \
    ccache \
    cmake3 \
    clang \
    @development-tools \
    doxygen \
    flexiblas-devel \
    flexiblas-openblas-serial \
    gdal-devel \
    glib2-devel \
    libasan \
    libubsan \
    micro \
    ninja-build \
    python3-devel \
    python3-numpy \
    python3-pip \
    sudo \
    texlive \
    && dnf clean all \
    && rm -rf /var/cache/yum

RUN flexiblas default openblas-serial

# Create a venv and activate it
RUN mkdir /venv && python3 -m venv /venv --system-site-packages

# Install pip packages, excluding any that were already installed by apt
COPY requirements.txt /
RUN bash -c '/venv/bin/pip install -r <(grep -vf <(pip3 freeze | cut -d= -f1) /requirements.txt)'

WORKDIR /work

COPY util/user_bootstrap.sh /
ENTRYPOINT ["/user_bootstrap.sh"]
CMD ["/bin/bash"]
